# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/masaüstü/yazılım ile ilgili herşey/excel çeviri programı/excel_ceviri.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1796, 721)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_s = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_s.setGeometry(QtCore.QRect(600, 140, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_s.setFont(font)
        self.comboBox_s.setObjectName("comboBox_s")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(840, 100, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(630, 100, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_ceviri = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ceviri.setGeometry(QtCore.QRect(650, 190, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_ceviri.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/1492608019-18-google-translate-text-language-translation_83386.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ceviri.setIcon(icon)
        self.pushButton_ceviri.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_ceviri.setObjectName("pushButton_ceviri")
        self.pushButton_ceviriKaydet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ceviriKaydet.setGeometry(QtCore.QRect(580, 440, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_ceviriKaydet.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/discet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ceviriKaydet.setIcon(icon1)
        self.pushButton_ceviriKaydet.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_ceviriKaydet.setObjectName("pushButton_ceviriKaydet")
        self.pushButton_excel_kaydet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_excel_kaydet.setGeometry(QtCore.QRect(650, 310, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_excel_kaydet.setFont(font)
        self.pushButton_excel_kaydet.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ico/Icons8-Ios7-Logos-Excel-Copyrighted.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_excel_kaydet.setIcon(icon2)
        self.pushButton_excel_kaydet.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_excel_kaydet.setObjectName("pushButton_excel_kaydet")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(580, 570, 211, 48))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.textEdit_source = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_source.setGeometry(QtCore.QRect(10, 0, 561, 641))
        self.textEdit_source.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEdit_source.setFont(font)
        self.textEdit_source.setObjectName("textEdit_source")
        self.pushButton_word = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_word.setGeometry(QtCore.QRect(750, 310, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_word.setFont(font)
        self.pushButton_word.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ico/1486565572-microsoft-office-word_81551.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_word.setIcon(icon3)
        self.pushButton_word.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_word.setObjectName("pushButton_word")
        self.pushButton_notepad = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_notepad.setGeometry(QtCore.QRect(860, 310, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_notepad.setFont(font)
        self.pushButton_notepad.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ico/Tatice-Cristal-Intense-Notepad-Bloc-notes.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_notepad.setIcon(icon4)
        self.pushButton_notepad.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_notepad.setObjectName("pushButton_notepad")
        self.textEdit_target = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_target.setGeometry(QtCore.QRect(1060, 0, 711, 631))
        self.textEdit_target.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEdit_target.setFont(font)
        self.textEdit_target.setObjectName("textEdit_target")
        self.pushButton_mailSend = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_mailSend.setGeometry(QtCore.QRect(950, 510, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_mailSend.setFont(font)
        self.pushButton_mailSend.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ico/Graphicloads-100-Flat-2-Email.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_mailSend.setIcon(icon5)
        self.pushButton_mailSend.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_mailSend.setObjectName("pushButton_mailSend")
        self.textEdit_mail = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_mail.setGeometry(QtCore.QRect(690, 510, 241, 41))
        self.textEdit_mail.setObjectName("textEdit_mail")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(580, 500, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(580, 260, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_excell = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_excell.setGeometry(QtCore.QRect(890, 10, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_excell.setFont(font)
        self.pushButton_excell.setObjectName("pushButton_excell")
        self.textEdit_wordCaunt = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_wordCaunt.setGeometry(QtCore.QRect(700, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_wordCaunt.setFont(font)
        self.textEdit_wordCaunt.setObjectName("textEdit_wordCaunt")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(580, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_ceviriKaydet_orijinal = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ceviriKaydet_orijinal.setGeometry(QtCore.QRect(580, 380, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_ceviriKaydet_orijinal.setFont(font)
        self.pushButton_ceviriKaydet_orijinal.setIcon(icon1)
        self.pushButton_ceviriKaydet_orijinal.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_ceviriKaydet_orijinal.setObjectName("pushButton_ceviriKaydet_orijinal")
        self.comboBox_t = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_t.setGeometry(QtCore.QRect(820, 140, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_t.setFont(font)
        self.comboBox_t.setObjectName("comboBox_t")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(580, 50, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.textEdit_excel_isim = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_excel_isim.setGeometry(QtCore.QRect(700, 50, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_excel_isim.setFont(font)
        self.textEdit_excel_isim.setObjectName("textEdit_excel_isim")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 650, 1781, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox_s.setCurrentText(_translate("MainWindow", "choose language"))
        self.comboBox_s.setItemText(0, _translate("MainWindow", "choose language"))
        self.comboBox_s.setItemText(1, _translate("MainWindow", "Türkçe"))
        self.comboBox_s.setItemText(2, _translate("MainWindow", "English"))
        self.comboBox_s.setItemText(3, _translate("MainWindow", "Español"))
        self.comboBox_s.setItemText(4, _translate("MainWindow", "Deutsch"))
        self.comboBox_s.setItemText(5, _translate("MainWindow", "Português"))
        self.comboBox_s.setItemText(6, _translate("MainWindow", "Polski"))
        self.comboBox_s.setItemText(7, _translate("MainWindow", "Italiano"))
        self.comboBox_s.setItemText(8, _translate("MainWindow", "Hrvatski"))
        self.comboBox_s.setItemText(9, _translate("MainWindow", "Nederlands"))
        self.comboBox_s.setItemText(10, _translate("MainWindow", "Dansk"))
        self.comboBox_s.setItemText(11, _translate("MainWindow", "Lietuvių"))
        self.comboBox_s.setItemText(12, _translate("MainWindow", "Eesti"))
        self.comboBox_s.setItemText(13, _translate("MainWindow", "Français"))
        self.comboBox_s.setItemText(14, _translate("MainWindow", "Arabic (United Arab Emirates)"))
        self.comboBox_s.setItemText(15, _translate("MainWindow", "Japanese (Japan)"))
        self.comboBox_s.setItemText(16, _translate("MainWindow", "Korean (South Korea)"))
        self.comboBox_s.setItemText(17, _translate("MainWindow", "Russian (Russia)"))
        self.comboBox_s.setItemText(18, _translate("MainWindow", "Chinese, Mandarin (Simplified, China)"))
        self.comboBox_s.setItemText(19, _translate("MainWindow", "Bulgarian"))
        self.comboBox_s.setItemText(20, _translate("MainWindow", "Czech"))
        self.comboBox_s.setItemText(21, _translate("MainWindow", "Danish"))
        self.comboBox_s.setItemText(22, _translate("MainWindow", "Greek"))
        self.comboBox_s.setItemText(23, _translate("MainWindow", "Finnish"))
        self.comboBox_s.setItemText(24, _translate("MainWindow", "Hebrew (Israel)"))
        self.comboBox_s.setItemText(25, _translate("MainWindow", "Hindi (India)"))
        self.comboBox_s.setItemText(26, _translate("MainWindow", "Croatian"))
        self.comboBox_s.setItemText(27, _translate("MainWindow", "Indonesian"))
        self.comboBox_s.setItemText(28, _translate("MainWindow", "Romanian"))
        self.comboBox_s.setItemText(29, _translate("MainWindow", "Serbian"))
        self.comboBox_s.setItemText(30, _translate("MainWindow", "Swedish"))
        self.comboBox_s.setItemText(31, _translate("MainWindow", "Ukrainian"))
        self.comboBox_s.setItemText(32, _translate("MainWindow", "Vietnamese"))
        self.comboBox_s.setItemText(33, _translate("MainWindow", "Afrikaans (South Africa)"))
        self.comboBox_s.setItemText(34, _translate("MainWindow", "Azerbaijani "))
        self.comboBox_s.setItemText(35, _translate("MainWindow", "Persian"))
        self.comboBox_s.setItemText(36, _translate("MainWindow", "Filipino"))
        self.comboBox_s.setItemText(37, _translate("MainWindow", "Swahili (Kenya)"))
        self.comboBox_s.setItemText(38, _translate("MainWindow", "Arabic (Saudi Arabia)"))
        self.comboBox_s.setItemText(39, _translate("MainWindow", "Arabic (Qatar)"))
        self.comboBox_s.setItemText(40, _translate("MainWindow", "Arabic (Kuwait)"))
        self.label_2.setText(_translate("MainWindow", "Target language"))
        self.label.setText(_translate("MainWindow", "Source language"))
        self.pushButton_ceviri.setText(_translate("MainWindow", "Translate"))
        self.pushButton_ceviriKaydet.setText(_translate("MainWindow", "Save translation as sound"))
        self.commandLinkButton.setText(_translate("MainWindow", "batuhanokmen.com"))
        self.label_3.setText(_translate("MainWindow", "Send mail"))
        self.label_4.setText(_translate("MainWindow", "Save as"))
        self.pushButton_excell.setText(_translate("MainWindow", "Start"))
        self.label_6.setText(_translate("MainWindow", "Word count :"))
        self.pushButton_ceviriKaydet_orijinal.setText(_translate("MainWindow", "Save word as sound"))
        self.comboBox_t.setCurrentText(_translate("MainWindow", "choose language"))
        self.comboBox_t.setItemText(0, _translate("MainWindow", "choose language"))
        self.comboBox_t.setItemText(1, _translate("MainWindow", "Türkçe"))
        self.comboBox_t.setItemText(2, _translate("MainWindow", "English"))
        self.comboBox_t.setItemText(3, _translate("MainWindow", "Español"))
        self.comboBox_t.setItemText(4, _translate("MainWindow", "Deutsch"))
        self.comboBox_t.setItemText(5, _translate("MainWindow", "Português"))
        self.comboBox_t.setItemText(6, _translate("MainWindow", "Polski"))
        self.comboBox_t.setItemText(7, _translate("MainWindow", "Italiano"))
        self.comboBox_t.setItemText(8, _translate("MainWindow", "Hrvatski"))
        self.comboBox_t.setItemText(9, _translate("MainWindow", "Nederlands"))
        self.comboBox_t.setItemText(10, _translate("MainWindow", "Dansk"))
        self.comboBox_t.setItemText(11, _translate("MainWindow", "Lietuvių"))
        self.comboBox_t.setItemText(12, _translate("MainWindow", "Eesti"))
        self.comboBox_t.setItemText(13, _translate("MainWindow", "Français"))
        self.comboBox_t.setItemText(14, _translate("MainWindow", "Arabic (United Arab Emirates)"))
        self.comboBox_t.setItemText(15, _translate("MainWindow", "Japanese (Japan)"))
        self.comboBox_t.setItemText(16, _translate("MainWindow", "Korean (South Korea)"))
        self.comboBox_t.setItemText(17, _translate("MainWindow", "Russian (Russia)"))
        self.comboBox_t.setItemText(18, _translate("MainWindow", "Chinese, Mandarin (Simplified, China)"))
        self.comboBox_t.setItemText(19, _translate("MainWindow", "Bulgarian"))
        self.comboBox_t.setItemText(20, _translate("MainWindow", "Czech"))
        self.comboBox_t.setItemText(21, _translate("MainWindow", "Danish"))
        self.comboBox_t.setItemText(22, _translate("MainWindow", "Greek"))
        self.comboBox_t.setItemText(23, _translate("MainWindow", "Finnish"))
        self.comboBox_t.setItemText(24, _translate("MainWindow", "Hebrew (Israel)"))
        self.comboBox_t.setItemText(25, _translate("MainWindow", "Hindi (India)"))
        self.comboBox_t.setItemText(26, _translate("MainWindow", "Croatian"))
        self.comboBox_t.setItemText(27, _translate("MainWindow", "Indonesian"))
        self.comboBox_t.setItemText(28, _translate("MainWindow", "Romanian"))
        self.comboBox_t.setItemText(29, _translate("MainWindow", "Serbian"))
        self.comboBox_t.setItemText(30, _translate("MainWindow", "Swedish"))
        self.comboBox_t.setItemText(31, _translate("MainWindow", "Ukrainian"))
        self.comboBox_t.setItemText(32, _translate("MainWindow", "Vietnamese"))
        self.comboBox_t.setItemText(33, _translate("MainWindow", "Afrikaans (South Africa)"))
        self.comboBox_t.setItemText(34, _translate("MainWindow", "Azerbaijani "))
        self.comboBox_t.setItemText(35, _translate("MainWindow", "Persian"))
        self.comboBox_t.setItemText(36, _translate("MainWindow", "Filipino"))
        self.comboBox_t.setItemText(37, _translate("MainWindow", "Swahili (Kenya)"))
        self.comboBox_t.setItemText(38, _translate("MainWindow", "Arabic (Saudi Arabia)"))
        self.comboBox_t.setItemText(39, _translate("MainWindow", "Arabic (Qatar)"))
        self.comboBox_t.setItemText(40, _translate("MainWindow", "Arabic (Kuwait)"))
        self.label_7.setText(_translate("MainWindow", "excel name :"))

import icons_rc
